version: 0.2

env:
  variables:
    CODE_SRC_DIR: "./terraform/live/ecs"
    TF_VERSION: "1.5.5"
    ECS_STATUS: "$(aws ecs describe-services --cluster dog-dev --services dog --no-cli-pager | jq '.services[].deployments[].rolloutState')"

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - "unzip -o terraform.zip -d /bin/"
      - "terraform -v"
  build:
    commands:
      - "cd ${CODEBUILD_SRC_DIR}/${CODE_SRC_DIR}"
      - "echo ## TERRAFORM PLAN : Generate the Terraform Plan"
      - "terraform init"
      - "terraform plan -out tfapply"
      - "jq"
artifacts:
  files:
    - '**/*'