version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo Build started on `date`
      - mvn clean package
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - echo $CODEBUILD_SOURCE_VERSION
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo $CODEBUILD_SRC_DIR
      - ls -ltr $CODEBUILD_SRC_DIR
  build:
    commands:
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:latest .
      - docker tag $IMAGE_REPO_NAME:latest $REPOSITORY_URI/$IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER
      - docker tag $IMAGE_REPO_NAME:latest $REPOSITORY_URI/$IMAGE_REPO_NAME:latest
      - docker images
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI/$IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER
      - docker push $REPOSITORY_URI/$IMAGE_REPO_NAME:latest
      - printf "[{\"name\":\"$IMAGE_REPO_NAME\",\"imageUri\":\"%s\"}]" $REPOSITORY_URI/$IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER > imagedefinitions.json
      - printf "\"image\" = \"%s\"" $REPOSITORY_URI/$IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER > z.auto.tfvars
      - cp z.auto.tfvars $CODEBUILD_SRC_DIR/terraform/live/ecs/
      - cp z.auto.tfvars $CODEBUILD_SRC_DIR/terraform/live/prodecs/
      - cat imagedefinitions.json

artifacts:
  files:
    - 'imagedefinitions.json'
    - './terraform/*'
  name: $IMAGE_REPO_NAME
