version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - "pip3 install checkov"
      - "checkov"
  build:
    commands:
      - CODE_SRC_DIR="./terraform/live/10_${ENVIRONMENT}ecs"
      - echo $CODE_SRC_DIR
      - checkov -d ${CODEBUILD_SRC_DIR}/${CODE_SRC_DIR} -o json | jq -r '.results.failed_checks[].check_name'      
      - checkov -d ${CODEBUILD_SRC_DIR}/${CODE_SRC_DIR} -o junitxml --soft-fail > checkov.xml
reports:
  checkov:
    files:
      - "checkov.xml"
    file-format: "JUNITXML"