version: 0.2

env:
  variables:
    CODE_SRC_DIR: "./terraform/live/10_${ENVIRONMENT}ecs"
    TF_VERSION: "1.5.5"

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - "unzip -o terraform.zip -d /bin/"
      - "terraform -v"
  build:
    commands:
      - "cd ${CODEBUILD_SRC_DIR}/${CODE_SRC_DIR}"
      - "echo ###### TERRAFORM APPLY ######"
      - "terraform apply tfapply"
      - "bash ${CODEBUILD_SRC_DIR}/scripts/ecs_${ENVIRONMENT}_status.sh"
artifacts:
  files:
    - '**/*'
  name: $IMAGE_REPO_NAME