version: 0.2

env:
  variables:
    CODE_SRC_DIR: "./terraform/live/10_${CUSTOM_VAR1}ecs"
    TF_VERSION: "1.5.5"

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - "unzip -o terraform.zip -d /bin/"
      - "terraform -v"
  build:
    commands:
      - "echo $CUSTOM_VAR1"
      - "echo $CODEBUILD_SRC_DIR"
      - "echo $CODE_SRC_DIR"
      - "ls -ltr"
      - "ls -ltr ${CODEBUILD_SRC_DIR}/${CODE_SRC_DIR}/"
      - "cp z.auto.tfvars.json ${CODEBUILD_SRC_DIR}/${CODE_SRC_DIR}/"
      - "cd ${CODEBUILD_SRC_DIR}/${CODE_SRC_DIR}"
      - "echo ## TERRAFORM PLAN : Generate the Terraform Plan"
      - "terraform init"
      - "terraform plan -out tfapply"
artifacts:
  files:
    - '**/*'
  name: $IMAGE_REPO_NAME